Update CONTRIBUTING.md
ImperialCollegeLondon/pyrealm pull request #146
Opened 2023-11-21 17:06 UTC by tztsai

## Fixes #144 

Add the instruction of using Git LFS in `CONTRIBUTING.md` to download the datasets, in order to pass two tests related to the dataset `inputs_data_24.25.nc`.

2023-11-24 10:16 UTC, MarionBWeinzierl requested changes
That should probably be enough info. Please fix the typo and add a link to more info about Git LFS (you can simply commit my suggestions for that).

2023-11-24 10:16 UTC, MarionBWeinzierl commented on CONTRIBUTING.md
> +The datasets in `pyreal_build_data` are stored via Git LFS. After cloning the repository,
```suggestion
The datasets in `pyrealm_build_data` are stored via [Git LFS](https://git-lfs.com/). After cloning the repository,
```

2023-11-24 11:34 UTC, MarionBWeinzierl commented
There is now a formatting error flagged by the linting which needs to be resolved: 
![image](https://github.com/ImperialCollegeLondon/pyrealm/assets/56403724/ef4930f8-1fdd-4f5d-bfb3-d3456b71f657)

2023-11-24 12:28 UTC, MarionBWeinzierl commented
Now it has trailing whitespace (don't worry, happens to me all the time!):
![image](https://github.com/ImperialCollegeLondon/pyrealm/assets/56403724/705e3d1f-0d78-4be6-8342-ac4ca23635da)

2023-11-24 13:38 UTC, davidorme commented
This shouldn't happen if `pre-commit` is installed? @TZTsai - have you got `pre-commit` set up on your machine? If you have then it shouldn't permit you to push commits that fail the `qa` action.

2023-11-24 21:05 UTC, tztsai commented
> This shouldn't happen if `pre-commit` is installed? @TZTsai - have you got `pre-commit` set up on your machine? If you have then it shouldn't permit you to push commits that fail the `qa` action. That's actually described in `CONTRIBUTING.md` 😄

Ah sorry. I do have `pre-commit` installed, but I directly edited the file on GitHub.

2023-11-24 21:11 UTC, davidorme commented
That explains it 😄

2023-11-27 08:41 UTC, MarionBWeinzierl approved these changes

2023-11-28 11:40 UTC, merged