Use a function `eval_poly` for polynomial evaluation
ImperialCollegeLondon/pyrealm pull request #187
Opened 2024-02-27 11:30 UTC by tztsai

# Description

A function `eval_poly` is implemented in `pyrealm.core.utilities` using Horner's method for polynomial evaluation and used to simplify H2O density calculation and specific heat calculation of air.

Fixes #167 

## Type of change

- [x] Optimization (back-end change that speeds up the code)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

2024-02-28 13:24 UTC, davidorme commented on pyrealm/core/utilities.py
> +    """Evaluates a polynomial with coefficients cf at the values in x.
And maybe a slightly longer name that gives that info (`evaluate_horner_polynomial`)?

2024-03-01 11:31 UTC, tztsai commented on pyrealm/core/utilities.py
> +    """Evaluates a polynomial with coefficients cf at the values in x.
I have addressed these now

2024-03-06 11:43 UTC, davidorme requested changes
I've pushed a minor change to the docstring to use math notation (and to show the change in equation form, rather than a specific evaluation) but otherwise this looks great.

I forgot one thing - can you add some simple unit tests? It doesn't need to be complex - a few example sets of coefficients and some $x$ values that can then be assessed using the 'normal' form and the new function? Something with a few different parameter sets that basically does this:

```python
import numpy as np
from pyrealm.core.utilities import evaluate_horner_polynomial

cf = np.array([5,4,3,2])
x = 2

normal = np.sum(cf * np.power(x, range(len(cf))))
horner = evaluate_horner_polynomial(x, cf)
assert normal == horner
```

2024-03-13 21:30 UTC, davidorme requested changes
LGTM - some minor changes

2024-03-13 21:30 UTC, davidorme commented on tests/unit/core/test_evaluate_horner_polynomial.py
> +    for deg in range(10):
This is being super picky but it's good to have a bit more context in unit test.

```suggestion
    """Test the evaluate_horner_polynomial function.
    
    This checks that the normal form (a + bx + cx2 + dx3) and output from the
    horner form evaluation (a + x(b + x(c + dx))) are equivalent for powers up to 10.
    """
    for deg in range(10):
```

2024-03-13 21:30 UTC, davidorme commented on tests/unit/core/test_evaluate_horner_polynomial.py
> +        x = np.random.rand()
Mostly just to check it all works with negative values 😄 Could equally use a uniform distribution in [-1, 1].

```suggestion
        cf = np.random.normal(deg + 1)
        x = np.random.normal()
```

2024-03-19 09:58 UTC, davidorme commented
I fixed the `qa` failure - somehow a `black` issue had snuck past pre-commit. The tests are failing but I think the `docs` failure is a VM fail - it runs on the `push` but not on the `pr` event.

2024-03-27 11:49 UTC, tztsai commented
> I've pushed an update of the failing test and expanded it a bit to make sure it handles different inputs. Can you make sure you run `pytest` before pushing commits? Particularly when working on tests, making sure that things run locally before setting off GitHub Actions can save a lot of waiting around!

Thanks for the update!

2024-03-28 09:40 UTC, merged